project:
  type: website

resources:
  - CNAME

website: 
  title: "SLU Bioinformatics Infrastructure"
  description: Slubi homepage
  navbar:
    logo: images/SLUBI_logo.png
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/SLUBioinformaticsInfrastructure/quarto_homepage
  sidebar:
    style: "floating"
    border: true
    bread-crumbs: false
    contents:
      - section: "Home"
        contents:
          - index.qmd
      - section: "Services"
        contents:
          - support_what.qmd
          - dropin.qmd
      - section: "Training"
        contents:
          - courses.qmd
          - workshops.qmd
          - learning-resources.qmd
          - online-resources.qmd
          - dardel.qmd
          - hpc2n.qmd
      - section: "Events"
        contents: 
          - events.qmd
          - social.qmd
      - section: "About us"
        contents: 
          - slubi.qmd
          - contact.qmd
          - board.qmd
          - publications.qmd
          - theses.qmd
      - section: "Archive"
        contents: 
          - news.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true